// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist_haversine
double dist_haversine(double lon_x, double lat_x, double lon_y, double lat_y);
RcppExport SEXP _kfbmisc_dist_haversine(SEXP lon_xSEXP, SEXP lat_xSEXP, SEXP lon_ySEXP, SEXP lat_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_x(lon_xSEXP);
    Rcpp::traits::input_parameter< double >::type lat_x(lat_xSEXP);
    Rcpp::traits::input_parameter< double >::type lon_y(lon_ySEXP);
    Rcpp::traits::input_parameter< double >::type lat_y(lat_ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist_haversine(lon_x, lat_x, lon_y, lat_y));
    return rcpp_result_gen;
END_RCPP
}
// dist_spherical_cosine
double dist_spherical_cosine(double lon_x, double lat_x, double lon_y, double lat_y);
RcppExport SEXP _kfbmisc_dist_spherical_cosine(SEXP lon_xSEXP, SEXP lat_xSEXP, SEXP lon_ySEXP, SEXP lat_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_x(lon_xSEXP);
    Rcpp::traits::input_parameter< double >::type lat_x(lat_xSEXP);
    Rcpp::traits::input_parameter< double >::type lon_y(lon_ySEXP);
    Rcpp::traits::input_parameter< double >::type lat_y(lat_ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist_spherical_cosine(lon_x, lat_x, lon_y, lat_y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_distm_C
NumericMatrix rcpp_parallel_distm_C(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _kfbmisc_rcpp_parallel_distm_C(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_distm_C(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_distm_C_min
IntegerVector rcpp_parallel_distm_C_min(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _kfbmisc_rcpp_parallel_distm_C_min(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_distm_C_min(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_distm_C_min_nonself
IntegerVector rcpp_parallel_distm_C_min_nonself(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _kfbmisc_rcpp_parallel_distm_C_min_nonself(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_distm_C_min_nonself(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_nearest_facility
NumericMatrix rcpp_parallel_nearest_facility(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _kfbmisc_rcpp_parallel_nearest_facility(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_nearest_facility(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_nearest_facility_nonself
NumericMatrix rcpp_parallel_nearest_facility_nonself(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _kfbmisc_rcpp_parallel_nearest_facility_nonself(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_nearest_facility_nonself(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kfbmisc_dist_haversine", (DL_FUNC) &_kfbmisc_dist_haversine, 4},
    {"_kfbmisc_dist_spherical_cosine", (DL_FUNC) &_kfbmisc_dist_spherical_cosine, 4},
    {"_kfbmisc_rcpp_parallel_distm_C", (DL_FUNC) &_kfbmisc_rcpp_parallel_distm_C, 2},
    {"_kfbmisc_rcpp_parallel_distm_C_min", (DL_FUNC) &_kfbmisc_rcpp_parallel_distm_C_min, 2},
    {"_kfbmisc_rcpp_parallel_distm_C_min_nonself", (DL_FUNC) &_kfbmisc_rcpp_parallel_distm_C_min_nonself, 2},
    {"_kfbmisc_rcpp_parallel_nearest_facility", (DL_FUNC) &_kfbmisc_rcpp_parallel_nearest_facility, 2},
    {"_kfbmisc_rcpp_parallel_nearest_facility_nonself", (DL_FUNC) &_kfbmisc_rcpp_parallel_nearest_facility_nonself, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_kfbmisc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
