# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert degrees to radians
#'
#' @param degree Degree value
#' @return Radian value (double)
NULL

#' Compute Haversine distance between two points
#'
#' @param lat1 Latitude for starting point
#' @param lon1 Longitude for starting point
#' @param lat2 Latitude for ending point
#' @param lon2 Longitude for ending point
#' @return Double of distance between coordinate pairs in km
#' @export
haversine <- function(lat1, lon1, lat2, lon2) {
    .Call('_kfbmisc_haversine', PACKAGE = 'kfbmisc', lat1, lon1, lat2, lon2)
}

#'
#' @export
rcpp_haversine_mat <- function(lon1, lat1, lon2, lat2) {
    .Call('_kfbmisc_rcpp_haversine_mat', PACKAGE = 'kfbmisc', lon1, lat1, lon2, lat2)
}

#'
#' @export
rcpp_haversine_mat_symmetric <- function(lon1, lat1, lon2, lat2) {
    .Call('_kfbmisc_rcpp_haversine_mat_symmetric', PACKAGE = 'kfbmisc', lon1, lat1, lon2, lat2)
}

#' Haversine Distance
#'
#' @param lon_x Longitude for starting point
#' @param lat_x Latitude for starting point
#' @param lon_y Longitude for ending point
#' @param lat_x Latitude for ending point
#'
#' @return Double of distance between points in m
#'
dist_haversine <- function(lon_x, lat_x, lon_y, lat_y) {
    .Call('_kfbmisc_dist_haversine', PACKAGE = 'kfbmisc', lon_x, lat_x, lon_y, lat_y)
}

#' Spherical Distance
#'
#' @param lon_x Longitude for starting point
#' @param lat_x Latitude for starting point
#' @param lon_y Longitude for ending point
#' @param lat_x Latitude for ending point
#'
#' @return Double of distance between points in m
#'
dist_spherical_cosine <- function(lon_x, lat_x, lon_y, lat_y) {
    .Call('_kfbmisc_dist_spherical_cosine', PACKAGE = 'kfbmisc', lon_x, lat_x, lon_y, lat_y)
}

#' Parallel calculates distance between two matrices of lat/long.
#'
#' @param x. matrix of coordinates. In the same format as st_coordinates output (X, Y)
#' @param y. matrix of coordinates. In the same format as st_coordinates output (X, Y)
#'
#' @return returns matrix of distances in miles
#'
rcpp_parallel_distm_C <- function(x, y) {
    .Call('_kfbmisc_rcpp_parallel_distm_C', PACKAGE = 'kfbmisc', x, y)
}

#'  Find closest unit from group y
#'
#'  @param x. matrix of coordinates. In the same format as st_coordinates output (X, Y)
#'  @param y. matrix of coordinates. In the same format as st_coordinates output (X, Y)
#'
#'  @return Vector. Contains index of closest unit in y
#'
#'  @export
rcpp_parallel_distm_C_min <- function(x, y) {
    .Call('_kfbmisc_rcpp_parallel_distm_C_min', PACKAGE = 'kfbmisc', x, y)
}

#'  Find closest unit from group y and measured distance
#'
#'  @param x. matrix of coordinates. In the same format as st_coordinates output (X, Y)
#'  @param y. matrix of coordinates. In the same format as st_coordinates output (X, Y)
#'
#'  @return Matrix. 2 columns. First column is index of closest unit in y.
#'  Second column is distance
#'
#'  @export
rcpp_parallel_nearest_facility <- function(x, y) {
    .Call('_kfbmisc_rcpp_parallel_nearest_facility', PACKAGE = 'kfbmisc', x, y)
}

